### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Niduin** [BlackJar72/DoomlikeDungeons#27]
[latest.log](https://github.com/BlackJar72/DoomlikeDungeons/files/3489954/latest.log)

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Doomlike Dungeons (dldungeonsjbg)
Caused by: java.lang.NullPointerException
	at jaredbgreat.dldungeons.pieces.chests.LootItem$ItemPrototype.hashCode(LootItem.java:63)
	at java.util.HashMap.hash(Unknown Source)
	at java.util.HashMap.containsKey(Unknown Source)
	at jaredbgreat.dldungeons.pieces.chests.LootItem.fixLevel(LootItem.java:133)
	at jaredbgreat.dldungeons.pieces.chests.LootItem.<init>(LootItem.java:91)
	at jaredbgreat.dldungeons.themes.ThemeReader.readLoot(ThemeReader.java:313)
	at jaredbgreat.dldungeons.themes.ThemeReader.openLoot(ThemeReader.java:257)
	at jaredbgreat.dldungeons.themes.ThemeReader.readThemes(ThemeReader.java:185)
	at jaredbgreat.dldungeons.DoomlikeDungeons.postInit(DoomlikeDungeons.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by BlackJar72** [comment]
I can put a failsafe here and warning message here, but you made a mistake editing the chests.cfg.  I don't get this with the default loot, and this error means some item was not recognized (Minecraft / Java saw it as _null_).

**Comment by BlackJar72** [comment]
The new version will ignore such mistakes and just skip the bad item, unless you configure it to cash on your errors.
