### ISSUE TITLE
[STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: java.lang.NullPointerException

### ISSUE THREAD

**Issue by edgaradr223** [BlackJar72/DoomlikeDungeons#36]
the following message its showing up in my console with the last version of doomlike dungeons, im also looking for the dungeon but it seems like its not generating at all, is this a known issue or there is something i can do to fix it? or its just something i can ignore? (no crash, 1.12.2)

[Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: java.lang.NullPointerException
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.nbt.tags.NBTGroup.write(NBTGroup.java:36)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.nbt.NBTHelper.setNbtTag(NBTHelper.java:45)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.pieces.chests.LootItem.getStack(LootItem.java:232)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.pieces.chests.LootCategory.getLoot(LootCategory.java:91)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.pieces.chests.TreasureChest.place(TreasureChest.java:78)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.planner.mapping.ChunkFeatures.buildTileEntites(ChunkFeatures.java:55)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.planner.mapping.ChunkFeatures.buildFeatures(ChunkFeatures.java:82)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.planner.mapping.MapMatrix.buildInChunk(MapMatrix.java:239)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.builder.Builder.buildDungeonChunk(Builder.java:101)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.builder.Builder.buildDungeonsChunk(Builder.java:108)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.GenerationHandler.findDungeonsToBuild(GenerationHandler.java:110)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.GenerationHandler.generate(GenerationHandler.java:81)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:990)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[02:20:32] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at java.lang.Thread.run(Thread.java:745)
[02:20:32] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 2777ms behind, skipping 55 tick(s)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: java.lang.NullPointerException
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.nbt.tags.NBTGroup.write(NBTGroup.java:36)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.nbt.NBTHelper.setNbtTag(NBTHelper.java:45)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.pieces.chests.LootItem.getStack(LootItem.java:232)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.pieces.chests.LootCategory.getLoot(LootCategory.java:91)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.pieces.chests.BasicChest.fillChest(BasicChest.java:99)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.pieces.chests.BasicChest.place(BasicChest.java:75)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.planner.mapping.ChunkFeatures.buildTileEntites(ChunkFeatures.java:55)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.planner.mapping.ChunkFeatures.buildFeatures(ChunkFeatures.java:82)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.planner.mapping.MapMatrix.buildInChunk(MapMatrix.java:239)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.builder.Builder.buildDungeonChunk(Builder.java:101)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.builder.Builder.buildDungeonsChunk(Builder.java:108)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.GenerationHandler.findDungeonsToBuild(GenerationHandler.java:110)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at jaredbgreat.dldungeons.GenerationHandler.generate(GenerationHandler.java:81)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:980)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[02:20:34] [Server thread/INFO] [STDERR]: [jaredbgreat.dldungeons.GenerationHandler:findDungeonsToBuild:112]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by BlackJar72** [comment]
This looks like a bug in customNBT for a special loot item -- it shouldn't acutally hurt anything, but it explains why I could never find The Wolfman's Wand, even after having many Axes of Iron Truth and Galactic Hiking Boots.

It does need to be fixed though, but it won't hurt your game.

**Comment by BlackJar72** [comment]
Yep, I typed a CL where and LC should be, causing to try to add a tag I hadn't defined, giving the null pointer exception -- which is now handled as fail-safe instead of fail-fast.  I'll fix that as soon as I'm back to my dev environment.  (Technically you could fix it on your computer by editing the last line of nbt.cfg -- its the very last tag in the file that's broken.)

**Comment by edgaradr223** [comment]
> Yep, I typed a CL where and LC should be, causing to try to add a tag I hadn't defined, giving the null pointer exception -- which is now handled as fail-safe instead of fail-fast. I'll fix that as soon as I'm back to my dev environment. (Technically you could fix it on your computer by editing the last line of nbt.cfg -- its the very last tag in the file that's broken.)


ok ok, fixed it, ill leave this link to the corrected file https://files.fm/f/j228cz5kr just in case someone comes with the same issue and doesnt know how to change it itself (which i doubt because its very easy) but just in case, just go into AppData\Roaming\.minecraft\config\DLDungeonsJBG and change your nbt.cfg to this one.

Thank you mate for this awesome mod and your fast reply.
